baseURL = 'https://explicitud.com/'
languageCode = 'es'
defaultContentLanguage = 'es'
title = 'Explicitud'
theme = 'hugo-theme-texty'

[[menus.main]]
name = 'Acerca de'
pageRef = '/acerca-de/'
weight = 20

[params]
  [params.social]
    instagram = "https://www.instagram.com/asiermarques/"
    medium = "https://medium.com/@asiermarques"
    twitter = ""