baseURL = 'https://explicitud.com/'
languageCode = 'es'
defaultContentLanguage = 'es'
title = 'Explicitud'
theme = 'hugo-theme-texty'

[[menus.main]]
name = 'Acerca de'
pageRef = '/acerca-de/'
weight = 20

[params]
  [params.social]
    instagram = "your-instagram-url"
    medium = "your-medium-url"
    twitter = "your-twitter-url"