baseURL = 'https://explicitud.com/'
languageCode = 'es'
defaultContentLanguage = 'es'
title = 'Explicitud'
theme = 'hugo-theme-texty'

[[menus.main]]
name = 'Acerca de'
pageRef = '/acerca-de/'
weight = 20

[params]
  description = "Explicitud, textos y microrelatos."
  [params.social]
    instagram = "https://www.instagram.com/asiermarques/"
    medium = "https://medium.com/@asiermarques"
    twitter = ""
  [params.footer]
    copyright = "© %d Textos creados por <a rel=\"cc:attributionURL dct:creator\" property=\"cc:attributionName\" href=\"https://asiermarques.com\">Asier Marqués</a> <a href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY-NC-ND 4.0<img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1\" alt=\"\"></a>"
